export const ERROR_CODE_NONE = 0;
export const ERROR_CODE_BAD_REQUEST = 13;
export const ERROR_CODE_INVALID_EMAIL = 100;
export const ERROR_CODE_PARAMETER_NOT_PASSED = 101;
export const ERROR_CODE_USER_WITH_LOGIN_EXISTS = 102;
export const ERROR_CODE_USER_WITH_EMAIL_EXISTS = 103;
export const ERROR_CODE_USER_WITH_USERNAME_EXISTS = 104;
export const ERROR_CODE_USER_NOT_EXISTS = 105;

export const ERROR_MESSAGE_OK = 'OK';
