export const ERROR_CODE_NONE = 0;
export const ERROR_CODE_BAD_REQUEST = 13;
export const ERROR_CODE_INVALID_EMAIL = 100;
export const ERROR_CODE_PARAMETER_NOT_PASSED = 101;

export const ERROR_CODE_USER_WITH_LOGIN_EXISTS = 102;
export const ERROR_CODE_USER_WITH_EMAIL_EXISTS = 103;
export const ERROR_CODE_USER_WITH_USERNAME_EXISTS = 104;
export const ERROR_CODE_USER_NOT_EXISTS = 105;
export const ERROR_CODE_USER_WITH_PHONE_EXISTS = 106;

export const ERROR_CODE_CITY_WITH_NAME_RU_EXISTS = 107;
export const ERROR_CODE_CITY_WITH_NAME_KZ_EXISTS = 108;

export const ERROR_CODE_DEPARTMENT_WITH_NAME_RU_EXISTS = 109;
export const ERROR_CODE_DEPARTMENT_WITH_NAME_KZ_EXISTS = 110;
export const ERROR_CODE_DEPARTMENT_NOT_EXISTS = 106;

export const ERROR_CODE_STATUS_NOT_EXISTS = 107;
export const ERROR_CODE_STATUS_WITH_NAME_KZ_EXISTS = 108;
export const ERROR_CODE_STATUS_WITH_NAME_RU_EXISTS = 109;

export const ERROR_CODE_ROLE_WITH_NAME_RU_EXISTS = 110;
export const ERROR_CODE_ROLE_WITH_NAME_KZ_EXISTS = 111;
export const ERROR_CODE_ROLE_NOT_EXISTS = 112;

export const ERROR_CODE_CUSTOMER_WITH_NAME_RU_EXISTS = 113;
export const ERROR_CODE_CUSTOMER_WITH_NAME_KZ_EXISTS = 114;
export const ERROR_CODE_CUSTOMER_NOT_EXISTS = 115;

export const ERROR_CODE_CATEGORY_WITH_NAME_RU_EXISTS = 116;
export const ERROR_CODE_CATEGORY_WITH_NAME_KZ_EXISTS = 117;
export const ERROR_CODE_CATEGORY_NOT_EXISTS = 118;

export const ERROR_CODE_FAQ_WITH_QUESTION_RU_EXISTS = 119;
export const ERROR_CODE_FAQ_WITH_QUESTION_KZ_EXISTS = 120;
export const ERROR_CODE_FAQ_NOT_EXISTS = 121;

export const ERROR_MESSAGE_OK = 'OK';
