export const ERROR_CODE_NONE = 0;
export const ERROR_CODE_BAD_REQUEST = 13;
export const ERROR_CODE_INVALID_EMAIL = 100;
export const ERROR_CODE_PARAMETER_NOT_PASSED = 101;
export const ERROR_CODE_USER_WITH_LOGIN_EXISTS = 102;
export const ERROR_CODE_USER_WITH_EMAIL_EXISTS = 103;
export const ERROR_CODE_USER_WITH_USERNAME_EXISTS = 104;
export const ERROR_CODE_USER_NOT_EXISTS = 105;
export const ERROR_CODE_USER_WITH_PHONE_EXISTS = 106;
export const ERROR_CODE_CITY_WITH_NAME_RU_EXISTS = 107;
export const ERROR_CODE_CITY_WITH_NAME_KZ_EXISTS = 108;
export const ERROR_CODE_DEPARTMENT_WITH_NAME_RU_EXISTS = 109;
export const ERROR_CODE_DEPARTMENT_WITH_NAME_KZ_EXISTS = 110;

export const ERROR_MESSAGE_OK = 'OK';
